[package]
name = "naru-symbol"
version = "0.1.0"
authors = ["Eunchong Yu <kroisse@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
string_cache = "0.7"

[build-dependencies]
string_cache_codegen = "0.4"
