[package]
name = "urashima"
description = "Proof-of-concept Runtime for Naru Programming Language"
version = "0.1.0"
authors = ["Eunchong Yu <kroisse@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = { version = "1.0.91", features = ["derive"] }
string_cache = "0.7"

[build-dependencies]
string_cache_codegen = "0.4"

[dev-dependencies]
serde_json = "1.0.39"
