[package]
name = "libnaru"
version = "0.1.0"
authors = ["Eunchong Yu <kroisse@gmail.com>"]
edition = "2018"

[lib]
name = "naru"
crate-type = ["cdylib", "staticlib"]

[dependencies]
cstr_core = "0.1.2"
guard = "0.5"
libc = "0.2.58"
urashima = { path = ".." }

[build-dependencies]
cbindgen = "0.9"
